name: Dev
on:
  workflow_dispatch:
    inputs:
      release_enable:
        default: 'false'

#on: push
env:
  testV: "aaaa"
jobs: 
  dev-job:
    name: Build Test
    #runs-on: ubuntu-latest
    runs-on: dev
    steps:
    #- name: Clean All
    #  uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2

    - name: T1
      run: |
        echo "hi"
        echo "::set-output name=TEST_CHECK::true"
        echo "end"
      id: runEnv
    - name: T2
      run: |
        echo ${{ steps.runEnv.outputs.TEST_CHECK }}
    - name: T3
      run: |
        echo ${{ steps.runEnv.outputs.TEST_CHECK }}
    - name: T4
      run: |
        echo ${{ steps.runEnv.outputs.TEST_CHECK }}
    
      
    - name: s2
      run: |
        echo Hello, DEV!
        echo $GITHUB_REF
        git branch -a
        ls -al
        echo $testV
        testV="bbbb"
      
    - name: s1
      run: |
        echo Hello, DEV!
        echo $GITHUB_REF
        git branch -a
        ls -al
        echo "$testV"
    - name: test if 
      if: ${{ github.event.inputs.release_enable == 'true' && github.ref == 'refs/heads/master' }}
      run: |
        echo "test if v"
    
