name: Dev
on: [workflow_dispatch]
jobs: 
  dev-job:
    name: Build Test
    #runs-on: ubuntu-latest
    runs-on: dev
    steps:
    #- name: Clean All
    #  uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
      
    - name: s2
      run: |
        echo Hello, DEV!
        echo $GITHUB_REF
        git branch -a
        ls -al
        testV="aaaa"
      
    - name: s1
      run: |
        echo Hello, DEV!
        echo $GITHUB_REF
        git branch -a
        ls -al
        echo "$testV"
