name: Dev
on: [workflow_dispatch]
jobs: 
  dev-job:
    name: Build Test
    #runs-on: ubuntu-latest
    runs-on: dev
    steps:
    - name: Clean All
      uses: AutoModality/action-clean@v1
      
    - name: Run a one-line script
      run: |
        echo Hello, DEV!
        ls -al
