name: Dev
on: [workflow_dispatch]
#on: push
env:
  testV: "aaaa"
jobs: 
  dev-job:
    name: Build Test
    #runs-on: ubuntu-latest
    runs-on: dev
    steps:
    #- name: Clean All
    #  uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
      
    - name: s2
      run: |
        echo Hello, DEV!
        echo $GITHUB_REF
        git branch -a
        ls -al
        echo $testV
        testV="bbbb"
      
    - name: s1
      run: |
        echo Hello, DEV!
        echo $GITHUB_REF
        git branch -a
        ls -al
        echo "$testV"
    - name: test if 
      if 
      run: |
        echo "test if v"
    
