# This is a basic workflow to help you get started with Actions

name: CIAS

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: master


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  report:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #runs-on: dev
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: AutoModality/action-clean@v1
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo ${{ secrets.aaawqc }}
        
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Dev
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
